### ISSUE TITLE
New Update is incompatible with Gravelmon

### ISSUE THREAD

**Issue by ChaosDogG** [Arcaryx/Cobblemon-Integrations#1]
Exactly as the name suggests, it says that somewhere there is a null value where there should be a non-null value and I don't know wut that could mean. Here are the logs for ease of location:

[debug.log](https://github.com/Arcaryx/Cobblemon-Integrations/files/13245850/debug.log)

[latest.log](https://github.com/Arcaryx/Cobblemon-Integrations/files/13245849/latest.log)

**Comment by Arcaryx** [comment]
After digging through this with some others, it seems to be an incompatibility with Gravelmon. The error should occur regardless of creating a new world or joining an existing world. I'll get in contact with them and see what we can find, but until then I'll probably leave Gravelmon listed as an incompatibility. All other fakemon datapacks I've tried seem to be working without issue, so it's something specific to their implementation.

**Comment by Arcaryx** [comment]
Gravelmon has lots of work in progress Pokemon, and two happened to have null evolution results.
I added a simple check in cd4c8f5eb5036fd4a920615ff34077e4557bcb25 to ensure these issues are logged and skipped instead of crashing.
