### ISSUE TITLE
Issue with JADE

### ISSUE THREAD

**Issue by Blaize6363** [Arcaryx/Cobblemon-Integrations#10]
![image](https://github.com/user-attachments/assets/559f5b00-bf6c-4862-b8cb-7b4e1d562f4a)
This shows up when looking at the fossil restoration machine

**Comment by Arcaryx** [comment]
Are you updated to the latest version? If not, could you let me know if this is Fabric or Forge, singleplayer or multiplayer, and what other mods you are running?
