### ISSUE TITLE
 Crash when going threw sun stone in JEI

### ISSUE THREAD

**Issue by DraTrav** [Arcaryx/Cobblemon-Integrations#11]
[crash-2024-08-08_02.48.19-client.txt](https://github.com/user-attachments/files/16539602/crash-2024-08-08_02.48.19-client.txt)

Open the sunstone recipes in JEI scroll to the second page and it crashes

**Comment by Arcaryx** [comment]
I'm currently completely unable to replicate this. Could you load up just Cobblemon, Cobblemon Integrations, and JEI to see if this occurs? This is likely a mod incompatibility.

**Comment by DraTrav** [comment]
I'm unsure what changed but with everything updated it works now just fine. Maybe was on JEI's end? and it's fixed now
