### ISSUE TITLE
Forge version 1.0.7 doesn't show pokemon drops

### ISSUE THREAD

**Issue by RedGenesectNinja** [Arcaryx/Cobblemon-Integrations#14]
I recently noticed that the pokemon drops tab was missing from JEI when playing with the 1.0.7 version of Cobblemon Integrations. I switched back to 1.0.6 and the tab was present

**Comment by Arcaryx** [comment]
First can you try updating JEI to latest version? If that doesn't solve the problem, can you let me know if you're on Fabric or Forge?

**Comment by RedGenesectNinja** [comment]
My JEI is currently at version 15.12.2.51. I'll try updating JEI to the latest version and let you know if that fixes it. As stated in the title, I am playing with Forge

**Comment by RedGenesectNinja** [comment]
That seems to have done the trick. Thank you for the help
