### ISSUE TITLE
Minor mod incompatibility with Waystones

### ISSUE THREAD

**Issue by PinkVeganMason** [Arcaryx/Cobblemon-Integrations#3]
Mods included: latest version of Cobblemon, Cobblemon Integrations, and Waystones

Context: Put a Pokemon in the 1st slot of your party and a Pokemon in the 3rd slot of your party, leaving the 2nd slot empty (exact placement doesn't matter, just have a gap slot somewhere in the party)

Problem: If you send out a Pokemon that comes after the gap slot, you are unable to shift-rightclick that Pokemon to interact with it.

From my testing, this ONLY happens when Waystones specifically is installed. Disabling waystones makes the behavior go away; likewise, enabling waystones but disabling integrations makes the behavior go away as well.

**Comment by Arcaryx** [comment]
Thanks for letting me know, this will be fixed in 1.0.4 (fixed by c46184a816941d02f7bf9f0a26ddad8dad291576)
